import pandas as pd

t = ['SHSSCEGAAAYRCGGGS', 'SHSSCEGKGGRGCGGGS', 'SHSSCGDGGGKRCGGGS',
       'SHSSCGEGRGVGCGGGS', 'SHSSCGGRGGGWCGGGS', 'SHSSCGGSLGAWCGGGS',
       'SHSSCGGTLGAWCGGGS', 'SHSSCGGVWVGLCGGGS', 'SHSSCGGVWVVLCGGGS',
       'SHSSCGKDRALRCGGGS', 'SHSSCGLWARVGCGGGS', 'SHSSCGMWARVGCGGGS',
       'SHSSCGSGGGGGCGGGS', 'SHSSCGVTLGAWCGGGS', 'SHSSCHAPTNRLCGGGS',
       'SHSSCHNPTHPTCGGGS', 'SHSSCHNPTHQTCGGGS', 'SHSSCHPPSLRTCGGGS',
       'SHSSCIDGGGGFCGGGS', 'SHSSCKKPTHQTCGGGS', 'SHSSCKNQPGPHCGGGS',
       'SHSSCKPLTPPTCGGGS', 'SHSSCKPPTPQTCGGGS', 'SHSSCKQASAPTCGGGS',
       'SHSSCKQPTPPHCGGGS', 'SHSSCKQQTPVGCGGGS', 'SHSSCKSTTPHTCGGGS',
       'SHSSCKTTTPQTCGGGS', 'SHSSCLDGGGGFCGGGS', 'SHSSCLGTTHPRCGGGS',
       'SHSSCLQPPPPHCGGGS', 'SHSSCLWIGGGGCGGGS', 'SHSSCNKVTHQTCGGGS',
       'SHSSCNTTSDKNCGGGS', 'SHSSCPGPAAPACGGGS', 'SHSSCPPRPPTQCGGGS',
       'SHSSCPPTTATYCGGGS', 'SHSSCPQLSQQQCGGGS', 'SHSSCPQPWQQQCGGGS',
       'SHSSCPTRPQHACGGGS', 'SHSSCPWSPQPMCGGGS', 'SHSSCQALHASSCGGGS',
       'SHSSCQAPPLPACGGGS', 'SHSSCQAQHASSCGGGS', 'SHSSCQAQLASSCGGGS',
       'SHSSCQEQHPAMCGGGS', 'SHSSCQGLSWGMCGGGS', 'SHSSCRSLHEDFCGGGS',
       'SHSSCSPPQKLTCGGGS', 'SHSSCTAMTNPRCGGGS', 'SHSSCTAPSKRHCGGGS',
       'SHSSCTAPSQRNCGGGS', 'SHSSCTATQPQTCGGGS', 'SHSSCTGTLGPKCGGGS',
       'SHSSCTPTAPPTCGGGS', 'SHSSCTRLPPTTCGGGS', 'SHSSCVASTPTACGGGS',
       'SHSSCVPPHENTCGGGS', 'SHSSCVRDGGSGCGGGS', 'SHSSCWRPDGWSCGGGS']

t1 = ['SHSSCEGAAAYRCGGGS', 'SHSSCEGKGGRGCGGGS', 'SHSSCGDGGGKRCGGGS',
       'SHSSCGEGRGVGCGGGS', 'SHSSCGGRGGGWCGGGS', 'SHSSCGGSLGAWCGGGS',
       'SHSSCGGTLGAWCGGGS', 'SHSSCGGVWVGLCGGGS', 'SHSSCGGVWVVLCGGGS',
       'SHSSCGKDRALRCGGGS', 'SHSSCGLWARVGCGGGS', 'SHSSCGMWARVGCGGGS',
       'SHSSCGSGGGGGCGGGS', 'SHSSCGVTLGAWCGGGS', 'SHSSCHAPTNRLCGGGS',
       'SHSSCHNPTHPTCGGGS', 'SHSSCHNPTHQTCGGGS', 'SHSSCHPPSLRTCGGGS',
       'SHSSCIDGGGGFCGGGS', 'SHSSCKKPTHQTCGGGS', 'SHSSCKNQPGPHCGGGS',
       'SHSSCKPLTPPTCGGGS', 'SHSSCKPPTPQTCGGGS', 'SHSSCKQASAPTCGGGS',
       'SHSSCKQPTPPHCGGGS', 'SHSSCKQQTPVGCGGGS', 'SHSSCKSTTPHTCGGGS',
       'SHSSCKTTTPQTCGGGS', 'SHSSCLDGGGGFCGGGS', 'SHSSCLGTTHPRCGGGS',
       'SHSSCLQPPPPHCGGGS', 'SHSSCLWIGGGGCGGGS', 'SHSSCNKVTHQTCGGGS',
       'SHSSCNTTSDKNCGGGS', 'SHSSCPGPAAPACGGGS', 'SHSSCPPRPPTQCGGGS',
       'SHSSCPPTTATYCGGGS', 'SHSSCPQLSQQQCGGGS', 'SHSSCPQPWQQQCGGGS',
       'SHSSCPTRPQHACGGGS', 'SHSSCPWSPQPMCGGGS', 'SHSSCQALHASSCGGGS',
       'SHSSCQAPPLPACGGGS', 'SHSSCQAQHASSCGGGS', 'SHSSCQAQLASSCGGGS',
       'SHSSCQEQHPAMCGGGS', 'SHSSCQGLSWGMCGGGS', 'SHSSCRSLHEDFCGGGS',
       'SHSSCSPPQKLTCGGGS', 'SHSSCTAMTNPRCGGGS', 'SHSSCTAPSKRHCGGGS',
       'SHSSCTAPSQRNCGGGS', 'SHSSCTATQPQTCGGGS', 'SHSSCTGTLGPKCGGGS',
       'SHSSCTPTAPPTCGGGS', 'SHSSCTRLPPTTCGGGS', 'SHSSCVASTPTACGGGS',
       'SHSSCVPPHENTCGGGS', 'SHSSCVRDGGSGCGGGS', 'SHSSCWRPDGWSCGGGS']

for i in range(len(t)):
    if t[i] != t1[i]:
        print(f"Difference at index {i}: {t[i]} != {t1[i]}")